// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static myfirstmodule.proxies.Image createImage(IContext context, myfirstmodule.proxies.User _user)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("User", _user == null ? null : _user.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.CreateImage").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Image.initialize(context, result);
	}
	public static boolean imageValidation(IContext context, myfirstmodule.proxies.Image _image)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Image", _image == null ? null : _image.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.ImageValidation").withParams(params).execute(context);
	}
}